export const users = [
    {
        id: 1,
        name: 'Willian',
        role: 'QA',
        address: 'Francisco de Montejo',
        salary: 10000,
    },
    {
        id: 2,
        name: 'Francisco',
        role: 'Desarrollador',
        address: 'Pensiones',
        salary: 987654,
    },
    {
        id: 3,
        name: 'Sinuhe',
        role: 'Desarrollador',
        address: 'Las americas',
        salary: 78974531,
    },
    {
        id: 4,
        name: 'Roger',
        role: 'Desarrollador',
        address: 'Las americas',
        salary: 132549854,
    },
    {
        id: 5,
        name: 'Abelardo',
        role: 'QA',
        address: 'Francisco de Montejo',
        salary: 9876512321,
    },
    {
        id: 6,
        name: 'Emilio',
        role: 'Marketing',
        address: 'Los heroes',
        salary: 9841321019,
    },   {
        id: 7,
        name: 'Pukardo',
        role: 'Ventas',
        address: 'Altabrisa',
        salary: 498416516,
    },   {
        id: 8,
        name: 'Franco',
        role: 'Ventas',
        address: 'Altabrisa',
        salary: 98465165,
    },   {
        id: 9,
        name: 'Bruno',
        role: 'Limpieza',
        address: 'Cholul',
        salary: 20,
    },
];